---------------------------------------------------
-- Glassware Distributions And Sandbox Spawn File          --
---------------------------------------------------
---please don't yell at me I tried to comment every distro table I know this is a nigthmare but it works. -- CrystalChris

local ItemSpawnChance = SandboxVars.Mixology.ItemChance

if (ItemSpawnChance == 1) then
    ItemSpawnChance = 0.05;
end

if (ItemSpawnChance == 2) then
    ItemSpawnChance = 0.15;
end

if (ItemSpawnChance == 3) then
    ItemSpawnChance = 0.50;
end

if (ItemSpawnChance == 4) then
    ItemSpawnChance = 1.0;
end

if (ItemSpawnChance == 5) then
    ItemSpawnChance = 1.5;
end

if (ItemSpawnChance == 6) then
    ItemSpawnChance = 2.0;
end

if (ItemSpawnChance == 7) then
    ItemSpawnChance = 3;
end

------------------------ Distros --------------------------------------

------------------------------
--- Glassware Spawn Chance ---
------------------------------
-- BarCounterGlasses
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.TeaStraw");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.TeaUmbrella");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.TumblerStraw");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.TumblerUmbrella");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.WineStraw");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.WineUmbrella");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["BarCounterGlasses"].items,  ItemSpawnChance * 8.20);



-- DishCabinetGeneric
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.TeaStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.TeaUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.TumblerStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.TumblerUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.WineStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.WineUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["DishCabinetGeneric"].items,  ItemSpawnChance * 0.9);

-- -- DishCabinetVIPLounge
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.TeaStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.TeaUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.TumblerStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.TumblerUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.WineStraw");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.WineUmbrella");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["DishCabinetVIPLounge"].items,  ItemSpawnChance * 0.9);

-- StoreKitchenGlasses
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["StoreKitchenGlasses"].items,  ItemSpawnChance * 0.9);

-- GigamartHousewares
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["GigamartHousewares"].items,  ItemSpawnChance * 0.9);

-- KitchenDishes
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.TeaStraw");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.TeaUmbrella");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.TumblerStraw");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.TumblerUmbrella");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.WineStraw");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.WineUmbrella");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["KitchenDishes"].items,  ItemSpawnChance * 0.9);

-- SpiffosKitchenCups
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.TeaStraw");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.TeaUmbrella");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.TumblerStraw");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.TumblerUmbrella");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.WineStraw");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.WineUmbrella");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.BeerGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 0.95);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 0.10);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.ChampagneGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.ColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.CherryColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.BlueishColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.CyanColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.DarkColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.GreenColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.IceColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.LemonColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.OrangeColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.PinkColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.PurpleColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.RedColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.RosaColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.YellowColaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.CoupeGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.HurricaneGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.MargaritaGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.MartiniGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.MilkshakeGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.RockGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.ShotGlass");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 8.20);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.Pitcher");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 5.40);
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["SpiffosKitchenCups"].items,  ItemSpawnChance * 0.9);


-- Antiques & PawnShop --
table.insert(ProceduralDistributions["list"]["Antiques"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["Antiques"].items,  ItemSpawnChance * 2.20);
table.insert(ProceduralDistributions["list"]["Antiques"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["Antiques"].items,  ItemSpawnChance * 3.20);
table.insert(ProceduralDistributions["list"]["Antiques"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["Antiques"].items,  ItemSpawnChance * 3.9);
table.insert(ProceduralDistributions["list"]["Antiques"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["Antiques"].items,  ItemSpawnChance * 3.20);
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items, "Mixology.RainbowColaGlass");
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items,  ItemSpawnChance * 3.20);
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items, "Mixology.PitcherKool");
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items,  ItemSpawnChance * 3.9);
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items, "Mixology.BootGlass");
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items,  ItemSpawnChance * 3.20);
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items, "Mixology.Chalice");
table.insert(ProceduralDistributions["list"]["PawnShopTools"].items,  ItemSpawnChance * 2.20);